# Matrix Inverse

The inverse of a square matrix $A$ is a matrix $A^{-1}$ such that

$$
AA^{-1}=A^{-1}A=I,
$$

where $I$ is the identity matrix. A matrix has an inverse only if it is **invertible**, which requires its determinant to be nonzero:

$$
\det(A)\neq0.
$$

In [1]:
import numpy as np

Consider the matrix

$$
A=
\begin{bmatrix}
2 & 1\\
5 & 3
\end{bmatrix}.
$$

The determinant of $A$ is evaluated first to determine whether the matrix is invertible.

In [2]:
A = np.array([[2, 1],
              [5, 3]])
A

array([[2, 1],
       [5, 3]])

For a $2\times2$ matrix,

$$
A=
\begin{bmatrix}
a & b\\
c & d
\end{bmatrix},
$$

the determinant is

$$
\det(A)=ad-bc.
$$

In [3]:
np.linalg.det(A)

np.float64(1.0000000000000009)

When $\det(A)\neq0$, the inverse has the closed-form expression

$$
A^{-1}=
\frac{1}{\det(A)}
\begin{bmatrix}
d & -b\\
-c & a
\end{bmatrix}.
$$

This expression provides the analytical inverse for a $2\times2$ matrix, while `np.linalg.inv` provides a general numerical implementation for invertible square matrices.

In [4]:
np.linalg.inv(A)

array([[ 3., -1.],
       [-5.,  2.]])

## Verifying the Inverse

The computed inverse can be verified by multiplying it by the original matrix:

$$
AA^{-1}=I.
$$

For the matrix above, the resulting product should be the $2\times2$ identity matrix,

$$
I=
\begin{bmatrix}
1 & 0\\
0 & 1
\end{bmatrix}.
$$

This provides a direct numerical verification that the computed matrix is indeed the inverse of $A$.

In [5]:
np.dot(A, np.linalg.inv(A))

array([[ 1.00000000e+00,  2.22044605e-16],
       [-8.88178420e-16,  1.00000000e+00]])