# Kronecker Product

The Kronecker product is an operation between two matrices that constructs a larger block matrix. For matrices $A$ and $B$, the Kronecker product is denoted by

$$
A\otimes B.
$$

If $A$ has dimensions $m\times n$ and $B$ has dimensions $p\times q$, then their Kronecker product has dimensions

$$
(mp)\times(nq).
$$

Using NumPy, the Kronecker product can be computed with `np.kron`.

In [1]:
import numpy as np

## Kronecker Product of Matrices

Consider the matrices

$$
A=
\begin{bmatrix}
1 & 2\\
3 & 4
\end{bmatrix},
\quad
B=
\begin{bmatrix}
0 & 1\\
1 & 0
\end{bmatrix}.
$$

The Kronecker product replaces each element of $A$ with a scaled copy of $B$:

$$
A\otimes B=
\begin{bmatrix}
1B & 2B\\
3B & 4B
\end{bmatrix}.
$$

Thus, a $2\times2$ matrix combined with another $2\times2$ matrix produces a $4\times4$ matrix.


In [2]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[0, 1],
              [1, 0]])

The operation can be evaluated directly using `np.kron(A, B)`.

In [3]:
np.kron(A, B)

array([[0, 1, 0, 2],
       [1, 0, 2, 0],
       [0, 3, 0, 4],
       [3, 0, 4, 0]])

## Block Structure

Consider another pair of matrices,

$$
A=
\begin{bmatrix}
1 & 2\\
3 & 4
\end{bmatrix},
\quad
B=
\begin{bmatrix}
0 & 5\\
6 & 7
\end{bmatrix}.
$$

The same block structure applies,

$$
A\otimes B=
\begin{bmatrix}
1B & 2B\\
3B & 4B
\end{bmatrix}.
$$

This illustrates that the Kronecker product is not an element-wise multiplication. Instead, every element of $A$ scales an entire copy of $B$.

In [4]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[0, 5],
              [6, 7]])

In [5]:
np.kron(A, B)

array([[ 0,  5,  0, 10],
       [ 6,  7, 12, 14],
       [ 0, 15,  0, 20],
       [18, 21, 24, 28]])

## Kronecker Product of Vectors

The Kronecker product can also be applied to vectors. Consider the two vectors

$$
|\psi\rangle=
\begin{bmatrix}
1\\
0
\end{bmatrix},
\quad
|\phi\rangle=
\begin{bmatrix}
0\\
1
\end{bmatrix}.
$$

Their Kronecker product is

$$
|\psi\rangle\otimes|\phi\rangle=
\begin{bmatrix}
1\\
0
\end{bmatrix}
\otimes
\begin{bmatrix}
0\\
1
\end{bmatrix}.
$$

The resulting vector has dimension $2\times2=4$ and represents the combined state of the two vector spaces.

In [6]:
psi = np.array([1, 0])
phi = np.array([0, 1])

In NumPy, the tensor product is computed using `np.kron(psi, phi)`.

In [7]:
np.kron(psi, phi)

array([0, 1, 0, 0])