# Vector Norm

The norm of a vector provides a measure of its magnitude or length. For a vector $\mathbf{v}$, the Euclidean norm is defined as

$$
|\mathbf{v}|_2=\sqrt{\sum_{i=1}^{n}|v_i|^2}.
$$

For a real-valued vector, this reduces to the familiar Euclidean length. In NumPy, the norm can be computed using `np.linalg.norm`.

In [1]:
import numpy as np

Consider the vector

$$
\mathbf{v}=
\begin{bmatrix}
3\\
4
\end{bmatrix}.
$$

In [2]:
v = np.array([3, 4])
v

array([3, 4])

Its Euclidean norm is

$$
|\mathbf{v}|_2=\sqrt{3^2+4^2}=5.
$$

In [3]:
np.linalg.norm(v)

np.float64(5.0)

## Vector Normalization

A vector can be normalized by dividing each component by its norm:

$$
\hat{\mathbf{v}}=\frac{\mathbf{v}}{|\mathbf{v}|}.
$$

The resulting vector has unit norm,

$$
|\hat{\mathbf{v}}|=1.
$$

In NumPy, normalization can therefore be performed by dividing the vector by `np.linalg.norm(v)`.

In [4]:
v / np.linalg.norm(v)

array([0.6, 0.8])

In [5]:
np.linalg.norm(v / np.linalg.norm(v))

np.float64(1.0)

## Row-wise Normalization

The norm operation can also be applied along a specific axis of a multidimensional array. Consider

$$
X=
\begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6\\
0 & 1 & 0
\end{bmatrix}.
$$

In [6]:
X = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [0, 1, 0]
])
X

array([[1, 2, 3],
       [4, 5, 6],
       [0, 1, 0]])

Using `axis=1`, the norm is computed independently for each row. With `keepdims=True`, the resulting norms retain a column dimension, allowing them to be broadcast directly during normalization.

In [7]:
np.linalg.norm(X, axis=1, keepdims=True)

array([[3.74165739],
       [8.77496439],
       [1.        ]])

Thus, each row can be normalized independently according to

$$
\hat{X}_{i}=\frac{X_i}{|X_i|_2}.
$$

In [8]:
X / np.linalg.norm(X, axis=1, keepdims=True)

array([[0.26726124, 0.53452248, 0.80178373],
       [0.45584231, 0.56980288, 0.68376346],
       [0.        , 1.        , 0.        ]])

## $p$-Norms

The norm is not restricted to the Euclidean norm. The general $p$-norm is defined as

$$
|\mathbf{v}|_p=\left(\sum_i |v_i|^p\right)^{1/p},\quad p\geq1.
$$

For example, the $1$-norm is

$$
|\mathbf{v}|_1=\sum_i |v_i|,
$$

while the $2$-norm corresponds to the Euclidean norm,

$$
|\mathbf{v}|_2=\sqrt{\sum_i |v_i|^2}.
$$

The infinity norm is defined as the largest absolute component,

$$
|\mathbf{v}|_\infty=\max_i |v_i|.
$$

These different norms provide different measures of vector magnitude and can be selected in NumPy using the `ord` parameter.

In [9]:
v = np.array([1, -2, 3])

In [10]:
np.linalg.norm(v, ord=1)

np.float64(6.0)

In [11]:
np.linalg.norm(v, ord=2)

np.float64(3.7416573867739413)

In [12]:
np.linalg.norm(v, ord=np.inf)

np.float64(3.0)

## Normalizing a Physical Vector

Normalization is also useful when a vector represents a physical quantity whose direction is important independently of its magnitude. Consider the vector

$$
\mathbf{F}=
\begin{bmatrix}
10\\
0\\
0
\end{bmatrix}.
$$

In [13]:
F = np.array([10, 0, 0])
F

array([10,  0,  0])

Its normalized form is

$$
\hat{\mathbf{F}}=\frac{\mathbf{F}}{|\mathbf{F}|_2}.
$$

The resulting vector has unit magnitude while preserving the direction of the original vector.

In [14]:
F / np.linalg.norm(F)

array([1., 0., 0.])

## Normalization of a Quantum State

Normalization is particularly important for quantum state vectors. A state $|\psi\rangle$ must satisfy

$$
\langle\psi|\psi\rangle=1.
$$

For a state with components $\psi_i$, this condition becomes

$$
\sum_i |\psi_i|^2=1.
$$

Therefore, an arbitrary nonzero state can be normalized according to

$$
|\hat{\psi}\rangle=\frac{|\psi\rangle}{\sqrt{\sum_i|\psi_i|^2}}.
$$

Consider

$$
|\psi\rangle=
\begin{bmatrix}
1\\
2\\
3\\
4
\end{bmatrix}.
$$

In [15]:
psi = np.array([1, 2, 3, 4], dtype=float)
psi

array([1., 2., 3., 4.])

The normalization factor is

$$
\sqrt{\sum_i|\psi_i|^2},
$$

and dividing each component by this factor produces a normalized state.

In [16]:
psi / np.sqrt(np.sum(np.abs(psi)**2))

array([0.18257419, 0.36514837, 0.54772256, 0.73029674])

The normalization can then be verified by evaluating

$$
\sum_i\left|\hat{\psi}_i\right|^2=1.
$$

In [17]:
np.sum(np.abs(psi / np.sqrt(np.sum(np.abs(psi)**2)))**2)

np.float64(0.9999999999999998)

This illustrates the connection between the mathematical vector norm and the normalization condition used for quantum states.