# Matrix Transpose

The transpose of a matrix is obtained by exchanging its rows and columns. For a matrix $A$, the transpose is denoted by $A^T$ and satisfies

$$
(A^T)_{ij}=A_{ji}.
$$

In [1]:
import numpy as np

Consider the matrix

$$
A=
\begin{bmatrix}
1 & 2\\
3 & 4
\end{bmatrix}.
$$

In [2]:
A = np.array([[1, 2],
              [3, 4]])
A

array([[1, 2],
       [3, 4]])

Taking the transpose exchanges the rows and columns,

$$
A^T=
\begin{bmatrix}
1 & 3\\
2 & 4
\end{bmatrix}.
$$

In NumPy, the transpose of an array can be obtained using the `.T` attribute.

In [3]:
A.T

array([[1, 3],
       [2, 4]])

## Conjugate Transpose

For complex-valued matrices, the transpose alone does not perform complex conjugation. The **conjugate transpose**, also known as the **Hermitian transpose**, combines both operations:

$$
A^\dagger=(A^*)^T,
$$

where $A^*$ denotes the element-wise complex conjugate.

Consider

$$
A=
\begin{bmatrix}
1+i & 2\\
3 & 4-i
\end{bmatrix}.
$$

In [4]:
A = np.array([[1+1j, 2],
              [3, 4-1j]])
A

array([[1.+1.j, 2.+0.j],
       [3.+0.j, 4.-1.j]])

The conjugate transpose is therefore

$$
A^\dagger=
\begin{bmatrix}
1-i & 3\\
2 & 4+i
\end{bmatrix}.
$$

In NumPy, this operation can be performed with `A.conj().T`.

In [5]:
A.conj().T

array([[1.-1.j, 3.-0.j],
       [2.-0.j, 4.+1.j]])