# Unitary Matrix

A unitary matrix is a square complex-valued matrix whose conjugate transpose is also its inverse. A matrix $U$ is unitary if

$$
U^\dagger U = UU^\dagger = I,
$$

where $U^\dagger$ denotes the conjugate transpose and $I$ is the identity matrix. Equivalently, the inverse of a unitary matrix is given by

$$
U^{-1}=U^\dagger.
$$

In [1]:
import numpy as np

Consider the matrix

$$
U=
\begin{bmatrix}
\frac{1}{\sqrt{2}} & \frac{1}{\sqrt{2}}\\
-\frac{1}{\sqrt{2}} & \frac{1}{\sqrt{2}}
\end{bmatrix}.
$$

Although the matrix contains only real-valued entries, it is initialized with a complex data type so that the same operations can be applied to general complex-valued unitary matrices.

In [2]:
U = np.array([[1/np.sqrt(2), 1/np.sqrt(2)],
              [-1/np.sqrt(2), 1/np.sqrt(2)]], dtype=complex)
U

array([[ 0.70710678+0.j,  0.70710678+0.j],
       [-0.70710678+0.j,  0.70710678+0.j]])

## Conjugate Transpose

The conjugate transpose of $U$ is

$$
U^\dagger=(U^*)^T.
$$

In NumPy, this can be computed as `np.conj(U.T)`. For real-valued matrices, the conjugation has no effect, so the conjugate transpose reduces to the ordinary transpose.

In [3]:
np.conj(U.T)

array([[ 0.70710678-0.j, -0.70710678-0.j],
       [ 0.70710678-0.j,  0.70710678-0.j]])

## Verifying Unitarity

The unitary condition can be verified by multiplying the conjugate transpose by the original matrix:

$$
U^\dagger U.
$$

For a unitary matrix, this product must equal the identity matrix,

$$
U^\dagger U=I.
$$

The identity matrix has the same dimension as $U$ and can be constructed in NumPy using `np.eye`.

In [4]:
np.dot(np.conj(U.T), U)

array([[ 1.00000000e+00+0.j, -2.23711432e-17+0.j],
       [-2.23711432e-17+0.j,  1.00000000e+00+0.j]])

To account for floating-point rounding errors, the numerical result can be compared with the identity matrix using `np.allclose`.

In [5]:
np.allclose(np.dot(np.conj(U.T), U), np.eye(U.shape[0]))

True

A result of `True` confirms that the matrix satisfies the unitary condition to within the numerical tolerance used by `np.allclose`.